apiVersion: apps/v1
kind: Deployment
metadata:
  name: p14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p14
  template:
    metadata:
      labels:
        app: p14
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p14
        ports:
        - containerPort: 80
